from src.chrono_client import MSSH

MSSH_COMMS={
    "setr":MSSH.c_setr,
    "mkDay":MSSH.c_create_day,
    "mkEvent":MSSH.c_create_event,
    "mkTime":MSSH.c_create_time,
    "days":MSSH.c_days,
    "mk":MSSH.c_mk,
    "show":MSSH.c_show,
    "times":MSSH.c_times,
    "genDays":MSSH.c_gen_days,
    "clear":MSSH.c_clear,
    "clearf":MSSH.c_clear_future,
    "getCurrent":MSSH.c_get_current,
    "today":MSSH.c_today,
    "day":MSSH.c_day,
    "changeEtime":MSSH.c_change_event_time,
    "changeEwhat":MSSH.c_change_event_what,
    "changeEtags":MSSH.c_change_event_tags,
    "changeEvent":MSSH.c_change_event,
    "delDay":MSSH.c_delete_day,
    "delEvent":MSSH.c_delete_event, 
    "end":MSSH.c_end,
    "plot":MSSH.c_plot_stats,
    "plotw":MSSH.c_plot_week,
    "note":MSSH.c_note,
    "notes":MSSH.c_todo,
    "deln":MSSH.c_del_note,
    "stats":MSSH.c_stats,
    "addRun":MSSH.c_add_run,
    "addSitup":MSSH.c_add_situp,
    "addPushup":MSSH.c_add_pushup,
    "addPlank":MSSH.c_add_plank,
    "merge":MSSH.c_merge,
    "heatmap":MSSH.c_heatmap,
    "split": MSSH.c_split_project,
    "ouras": MSSH.c_oura_sleep,
    "gets": MSSH.c_get_sleep,
    "sets": MSSH.c_set_sleep,
    "lns":MSSH.c_last_night_sleep,
    "debug": lambda _,b,*x: print(b,x)
}